Repository danielmrz-dev/projeto-angular-I, pull requests merged in 2024-11, with the labels that each got.

#7 Cria e configura estrutura do projeto
  .editorconfig
  .gitignore
  .vscode/extensions.json
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  angular.json
  package-lock.json
  package.json
  public/favicon.ico
  src/app/app-routing.module.ts
  src/app/app.component.html
  src/app/app.component.scss
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/styles/globalStyles.scss
  src/index.html
  src/main.ts
  src/styles.scss
  tsconfig.app.json
  tsconfig.json
  tsconfig.spec.json
Labels: documentation

#9 Cria pasta para agrupar os componentes
  src/app/app.module.ts
Labels: documentation

#17 Cria arquivo de variáveis e inicia a construção do componente modal-agendamento
  src/app/components/modal-agendamento/modal-agendamento.component.html
Labels: enhancement

#18 Branch/marcely
  package-lock.json
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.spec.ts
  src/app/components/header/header.component.ts
Labels: enhancement

#19 inicia aplicação header
  src/app/components/header/header.component.html
  src/app/components/header/header.component.ts
Labels: documentation

#22 cria componente tela-de-login, cria estrutura html do componente, cria pasta assets e edita angular.json
  src/app/components/tela-de-login/tela-de-login.component.html
  src/app/components/tela-de-login/tela-de-login.component.scss
  src/app/components/tela-de-login/tela-de-login.component.ts
Labels: enhancement

#23 mm
  angular.json
  src/app/app.component.html
  src/app/app.module.ts
  src/assets/background_tela-de-login.jpeg
Labels: enhancement

#24 Branch/cezaniltom
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/btn-inputs-form/btn-inputs-form.component.html
  src/app/components/btn-inputs-form/btn-inputs-form.component.scss
  src/app/components/btn-inputs-form/btn-inputs-form.component.ts
Labels: enhancement

#25 Branch/marcely
  src/app/app.component.css
  src/app/app.component.css.map
  src/app/app.component.html
  src/app/app.module.ts
  src/app/components/btn-confirma-pagamento/btn-confirma-pagamento.component.css
  src/app/components/btn-confirma-pagamento/btn-confirma-pagamento.component.css.map
  src/app/components/header/header.component.css
  src/app/components/header/header.component.css.map
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/info-agendamento/info-agendamento.component.css
  src/app/components/info-agendamento/info-agendamento.component.css.map
  src/app/components/modal-agendamento/modal-agendamento.component.css
  src/app/components/modal-agendamento/modal-agendamento.component.css.map
  src/app/components/tela-de-login/tela-de-login.component.css
  src/app/components/tela-de-login/tela-de-login.component.css.map
  src/styles.css
  src/styles.css.map
Labels: documentation, enhancement

#27 configura estilos do componente tela-de-login
  src/app/components/btn-confirma-pagamento/btn-confirma-pagamento.component.css
  src/app/components/btn-confirma-pagamento/btn-confirma-pagamento.component.css.map
  src/app/components/header/header.component.css
  src/app/components/header/header.component.css.map
  src/app/components/info-agendamento/info-agendamento.component.css
  src/app/components/info-agendamento/info-agendamento.component.css.map
  src/app/components/modal-agendamento/modal-agendamento.component.css
  src/app/components/modal-agendamento/modal-agendamento.component.css.map
  src/app/components/tela-de-login/tela-de-login.component.css
  src/app/components/tela-de-login/tela-de-login.component.css.map
  src/app/components/tela-de-login/tela-de-login.component.html
  src/app/components/tela-de-login/tela-de-login.component.scss
Labels: enhancement

#29 edita conteúdo do arquivo de estilos do componente tela-de-login
  src/app/app.component.html
  src/app/components/tela-de-login/tela-de-login.component.html
  src/app/components/tela-de-login/tela-de-login.component.scss
Labels: enhancement

#32 Cria rotas
  src/app/components/pages/page-agendamento/page-agendamento.component.html
  src/app/components/pages/page-agendamento/page-agendamento.component.scss
  src/app/components/pages/page-agendamento/page-agendamento.component.spec.ts
  src/app/components/pages/page-agendamento/page-agendamento.component.ts
Labels: enhancement

#35 Refatora header e formulário
  src/app/Interface/DadosInfo.interface.ts
  src/app/components/btn-inputs-form/btn-inputs-form.component.html
  src/app/components/btn-inputs-form/btn-inputs-form.component.scss
  src/app/components/header/header.component.html
  src/app/components/header/header.component.scss
  src/app/components/header/header.component.ts
  src/app/components/info-agendamento/info-agendamento.component.html
  src/app/components/info-agendamento/info-agendamento.component.scss
  src/app/components/info-agendamento/info-agendamento.component.ts
  src/app/components/modal-agendamento/modal-agendamento.component.html
  src/app/components/pages/page-agendamento/page-agendamento.component.html
  src/app/components/pages/page-agendamento/page-agendamento.component.scss
  src/app/components/tela-de-login/tela-de-login.component.scss
  src/app/interfaces/dados-info.interface.ts
  src/app/scss/_variables.scss
  src/index.html
Labels: Refactor

#39 Cria service para passar o nome de usuário de uma rota para outra
  src/app/app.module.ts
  src/app/components/btn-inputs-form/btn-inputs-form.component.html
  src/app/components/btn-inputs-form/btn-inputs-form.component.ts
  src/app/components/header/header.component.ts
  src/app/components/info-agendamento/info-agendamento.component.html
  src/app/components/info-agendamento/info-agendamento.component.ts
  src/app/components/pages/page-agendamento/page-agendamento.component.html
  src/app/components/pages/page-agendamento/page-agendamento.component.ts
  src/app/components/tela-de-login/tela-de-login.component.html
  src/app/components/tela-de-login/tela-de-login.component.ts
  src/app/services/nome-usuario.service.ts
Labels: Refactor

#40 Adiciona lógica de enviar o atendimento clicado para o modal
  src/app/components/btn-inputs-form/btn-inputs-form.component.html
  src/app/components/btn-inputs-form/btn-inputs-form.component.ts
  src/app/components/info-agendamento/info-agendamento.component.html
  src/app/components/info-agendamento/info-agendamento.component.scss
  src/app/components/info-agendamento/info-agendamento.component.ts
  src/app/components/modal-agendamento/modal-agendamento.component.html
  src/app/components/modal-agendamento/modal-agendamento.component.ts
  src/app/components/pages/page-agendamento/page-agendamento.component.html
  src/app/components/pages/page-agendamento/page-agendamento.component.spec.ts
  src/app/components/pages/page-agendamento/page-agendamento.component.ts
  src/app/components/tela-de-login/tela-de-login.component.scss
Labels: enhancement

#41 Adiciona spinner do Angular Material
  angular.json
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/header/header.component.ts
  src/app/components/info-agendamento/info-agendamento.component.ts
  src/app/components/modal-agendamento/modal-agendamento.component.html
  src/app/components/modal-agendamento/modal-agendamento.component.scss
  src/app/components/modal-agendamento/modal-agendamento.component.ts
  src/app/components/pages/page-agendamento/page-agendamento.component.html
  src/app/components/pages/page-agendamento/page-agendamento.component.ts
  src/app/pipes/preco.pipe.ts
  src/index.html
  src/styles.scss
Labels: enhancement
